const utils = require('../utils');
const axios = require('axios');

module.exports = {
    name: 'imagine',
    description: 'Generate AI images',
    category: 'media',
    react: '🖼️',
    alias: ['flux3', 'aiimage', 'generate'],
    usage: '.imagine <prompt>',
    example: '.imagine cat riding a bicycle',
    
    execute: async (sock, jid, msg, args, isGroup, isAdmin, isOwner) => {
        try {
            const prompt = args.join(' ').trim();
            
            if (!prompt) {
                await utils.sendBlueTickMessage(sock, jid,
                    `*🖼️ AI IMAGE GENERATOR*\n\n` +
                    `*Usage:* .imagine <description>\n` +
                    `*Example:* .imagine sunset beach\n\n` +
                    `*Powered by AI*`,
                    msg
                );
                return;
            }
            
            await utils.sendBlueTickMessage(sock, jid,
                `*🖼️ Generating...*\n"${prompt}"\n⏳ Please wait 10-20 seconds...`,
                msg
            );
            
            // AI Image API
            const apiUrl = `https://api.ryzendesu.com/api/ai/text2img?prompt=${encodeURIComponent(prompt)}`;
            const response = await axios.get(apiUrl, { timeout: 30000 });
            
            if (!response.data?.result) {
                throw new Error('API returned no image');
            }
            
            const imageUrl = response.data.result;
            const imageRes = await axios.get(imageUrl, { responseType: 'arraybuffer' });
            const imageBuffer = Buffer.from(imageRes.data);
            
            await sock.sendMessage(jid, {
                image: imageBuffer,
                caption: `*🖼️ AI GENERATED IMAGE*\n\n` +
                        `*Prompt:* ${prompt}\n` +
                        `*Style:* AI Art\n` +
                        `*Generated by:* SILA AI`,
                mimetype: 'image/jpeg'
            }, { quoted: msg });
            
        } catch (error) {
            console.error('Imagine error:', error);
            await utils.sendBlueTickMessage(sock, jid,
                `*❌ Generation failed!*\n` +
                `Error: ${error.message}\n\n` +
                `Try simpler prompts.`,
                msg
            );
        }
    }
};